### ISSUE TITLE
Enabled Applications don't show Checkmarks (Enabled/Disabled)

### ISSUE THREAD

**Issue by 2JayCee** [Skittyblock/Spectrum#3]
iPad 6th Gen
iOS 13.4.1
Checkra1n 1.0.1
Spectrum 1.0.1-1

The **Enabled Applications** doesn't show checkmarks next to the apps to show which apps are enabled/disabled.

**Comment by Skittyblock** [comment]
They show toggles, not checkmarks. Are the toggles not there?

**Comment by 2JayCee** [comment]
No nothing is shown. Probably because it's in iPad Layout whereas most users are on iPhone Layout. Also, I've switched to Kaleidoscope. No offense.
