### ISSUE TITLE
Spectrum Title is Off-Centered in iPad Landscape

### ISSUE THREAD

**Issue by 2JayCee** [Skittyblock/Spectrum#4]
iPad 6th Gen
iOS 13.4.1
Checkra1n 1.0.1
Spectrum 1.0.1-1

The Spectrum Title is off-centered in landscape and portrait mode. This appears to only be an iPad only problem. 
![File May 04, 10 34 01 AM](https://user-images.githubusercontent.com/7156758/80995274-deee9080-8df2-11ea-8bae-c76da9f38263.jpeg)

**Comment by Skittyblock** [comment]
fixed
